### ISSUE TITLE
Plone 5.1rc2 : Folder contents listing should be looking up edit actions on Archetypes content...

### ISSUE THREAD

**Issue by pfraterdeus** [plone/Plone#11]
When I'm in Plone 5.1rc2, Contents view and click the pencil (edit) icon on the row with my PFG folder, I get a 404 error. The displayed URL is .../@@edit
If I change this manually to .../edit the folder properties form comes up as expected.
It also works correctly when I click the edit button in the toolbar.

per @smcmahon
"You’ll want to file an issue on that for 5.1. The folder contents listing should be looking up edit actions on Archetypes content rather than just assuming @@edit will work. If it doesn’t or can’t get fixed, I’ll do a workaround in PFG."

Thanks for everything, Plonistas!
Plone 5 is amazing, can't even imagine where we'll be by 2020 ;-)

**Comment by tkimnguyen** [comment]
I have a funny feeling this will end up a lower priority fix in Plone, given that we are expecting to end support for Archetypes soon-ish. Even the notorious band of misfits who work on CastleCMS don't even try to support Archetypes 😬

**Comment by pfraterdeus** [comment]
@smcmahon said he’d jimmy something into PFG if it doesn’t get fixed in Plone…
But at least it’s on the record ;-)

**Comment by davisagli** [comment]
Fixed in https://github.com/plone/mockup/commit/ea455f785bab147d2a5ff1b503ea0574a0420b4c and https://github.com/plone/Products.CMFPlone/commit/22e19701eb5a1039bf97d53fba989c9a65dadb2e#diff-e288e485e9f8f1c32ff45c9e5e717a82
