### ISSUE TITLE
No code syntax highlighting

### ISSUE THREAD

**Issue by hanynowsky** [plone/Plone#14]
For companies writing technical content with programming code, syntax highlighting is a must.
This makes Plone useless for us even though it is powerful.
Do you know of how to make it possible?
I don't think we have the hand on hacking TinyMCE inside a Plone environment. As far as I know, TinyMCE comes with a plugin named 'Code Sample' which does syntax highlighting. But sounds like we cannot install it from PLone.

Is there any other possibility to use a different editor which supports code syntax highlighting?
Thanks

**Comment by gforcada** [comment]
There is indeed a plugin for TinyMCE: https://www.tiny.cloud/docs/plugins/codesample/ how to integrate it with Plone... that would be via mockup I guess (but do not quote me on that :sweat_smile: ).

As you closed the issue, I guess you ended up with something else? You could, if you still want, try to reach the wider plone community on their forums: https://community.plone.org
