### ISSUE TITLE
Small typo in README.rst

### ISSUE THREAD

**Issue by timgates42** [plone/Plone#17]
Should read plugable rather than pluggable.

**Comment by jugmac00** [comment]
Hi Tim, thanks for your contribution.

I am no native speaker, but pluggable seems to be the correct spelling, cf
https://www.merriam-webster.com/dictionary/pluggable

**Comment by tkimnguyen** [comment]
It is “pluggable”

**Comment by timgates42** [comment]
Thanks - sorry about that.
