### ISSUE TITLE
update README

### ISSUE THREAD

**Issue by mtrebron** [plone/Plone#21]
The plone.com site was retired, its content merged with plone.org
The Gitter chat was replaced by Discord

Also, please change link in project page "About" to plone.org

**Comment by mauritsvanrees** [comment]
The readme is a copy of the one from `Products.CMFPlone`. Should be fixed there as well. CMFPlone needs a few fixes in templates as well.

I have updated the About link on GitHub.

**Comment by rohnsha0** [comment]
Hi! Greeting from this side...
Can you assign this project to me... I'll do the asking changed.....

**Comment by wesleybl** [comment]
Hi @rohnsha0 !

You need to sign the Plone contributors agreement. To see:

https://plone.org/foundation/contributors-agreement
